spring.datasource.url= jdbc:mysql://localhost:3306/statistics
spring.datasource.username= statistics_user
spring.datasource.password= 1234
spring.jpa.hibernate.ddl-auto= update
spring.jpa.database-platform= org.hibernate.dialect.MySQLDialect

